#!/bin/bash

proc=$(ps aux)
pid=$(echo $proc | grep "/root/monitor/qstat.pl <CLUSTER>")
if [ -z "${pid}" ]; then
    #echo "Start <CLUSTER> QSTAT Job Sync ..." >> /var/www/symfony/var/log/monitoring.log
    perl /root/monitor/collectors/qstat.pl <CLUSTER> >> /var/www/symfony/var/log/monitoring.log 2>&1 &
fi
